defaults: &defaults
    macos:
      xcode: "11.7.0"
    shell: /bin/bash --login -eo pipefail
aliases:
  - &cache-pull
    keys:
      - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - gem-cache-v1-{{ arch }}-{{ .Branch }}
      - gem-cache-v1
  - &cache-push
    key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
    paths:
      - vendor/bundle
  - &prepare
    |
      git submodule update --init --recursive
      sudo gem install bundler
      bundle config set path 'vendor/bundle'
      bundle install
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  parseui:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache-pull
      - run: *prepare
      - save_cache: *cache-push
      - run: bundle exec rake test:parseui:all
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: build/reports
  carthage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *cache-pull
      - run: *prepare
      - save_cache: *cache-push
      - run: bundle exec rake test:carthage

workflows:
  version: 2
  pr:
    jobs:
      - parseui
      - carthage:
          requires:
            - parseui
  nightly:
    jobs:
      - carthage
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters: *filter-only-master
